global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend-hometail:9091']
    metrics_path: /metrics

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100'] # ðŸ‘ˆ 'node-exporter' à¸„à¸·à¸­à¸Šà¸·à¹ˆà¸­ service à¹ƒà¸™ docker-compose